### ISSUE TITLE
Warning: `key :ε is duplicated and overwritten on line 2461`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/unicode2latex#1]
When running Metanorma, I get this:

```
/Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/unicode2latex-0.0.1/lib/unicode2latex/unicode2latex.rb:2422: warning: key :ε is duplicated and overwritten on line 2461
```

**Comment by opoudjis** [comment]
That has already been debugged: https://github.com/metanorma/unicode2latex/commit/d1e1ff59135a947cae9f8a541d88dbe13185e6ef , and will be resolved in new release of gem.

In fact, I'll do the new release now.
